### ISSUE TITLE
Unlimited berries from Binnie leaves

### ISSUE THREAD

**Issue by SeriousCreeper** [Kiyaku/SeriousEngineering#2]
"This is a known bug with Binnie's Mods (see link below), and I saw you noticed it in the LP. But I figured I'd report it here for recordkeeping.

https://github(dot)com/ForestryMC/Binnie/issues/624"

**Comment by SeriousCreeper** [comment]
added a temporary fix using scavange - right clicking one of those berry bushes will give you berries once, and then get replaced by air. Will be available in 1.0.3

**Comment by dredgemage** [comment]
Just tested on version 1.0.3, some berry bushes (tested raspberry, redcurrent, and golden raspberry) still provide unlimited berries. 

Others (tested juniper, blueberry, and cranberry) when right-clicked will replace the block with air but the berry it gives you disappears when you try to eat it or move it in the inventory. 

(This only seems to hold true on world gen bushes because when I grow them from saplings they behave properly)

**Comment by SeriousCreeper** [comment]
Could you try 1.0.3.1? I added a few more in that version. 
And yeah unfortunately the berries being fake is how it's gonna have to be for now until they fix it. Each type of berry bush can have several meta values, so i'd have to go through them all and give out berries in a custom way. While not impossible, i rather see if binnies will fix that bug. 

Breaking them with a left click should give you the proper berries at least.

**Comment by dredgemage** [comment]
Tested 1.0.3.1. They all seem to break properly now. Hopefully Binnie's will fix this issue on their end soon.
